// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhfcypsnyilfxlbptemc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InloZmN5cHNueWlsZnhsYnB0ZW1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1MzgxMzQsImV4cCI6MjA1MTExNDEzNH0.wdoFdm1DpPxYRKuLltKdJM2WrrYLF80HDJbbicOySXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);